"""today_batch_items: per-user daily batch generated by B5.4 cron

Revision ID: 0010_today_batch_items
Revises: 0009_lock_tables_rekey
Create Date: 2026-05-12

Backs the B5.4 batch cron (project_phase5_send_model.md). Each row represents
ONE company outreach for ONE user on ONE date — the company-grouped send
model, not contact-grouped.

  - `to_contact_id`: the single TO recipient (random pick by the cron).
  - `cc_contact_ids`: JSON-encoded list[int] of up to 4 CC recipients at the
    same `company_domain`. Total recipients ≤ 5 per the Phase 5 spec.
  - `template_id`: nullable for v0 because templates (B5.7) haven't shipped;
    the cron renders a hardcoded default body. Once templates land we still
    allow null (e.g., manual edits without a saved template).
  - `subject` / `body`: pre-rendered at cron time so the user reviews exactly
    what will go out. Edits in /today PATCH update these fields.
  - `send_time`: the scheduled UTC send time. 1/hour starting 6am UTC for free
    (7 slots → 6am..12pm). Paid (20 slots) evenly distributed across the
    6am-8pm UTC window (~44min cadence). Per-user-timezone is future work;
    v0 runs in UTC.
  - `status`: 'default' (awaiting user review), 'ready' (user marked send, or
    autopilot user — cron set directly), 'skipped', 'sent', 'cooldown', 'held'.
    B5.5 send worker drains 'ready'; B5.6 reply ingestion can flip to 'held'.

The `(user_id, batch_date, company_id)` unique constraint enforces idempotency:
re-running the cron for the same user on the same day is a no-op (the service
layer short-circuits before insertion, but this is the belt-and-suspenders
guarantee at the DB).

send_queue (from 0001_init) stays contact-keyed for now. B5.5 will translate
today_batch_items rows into send_queue rows at dispatch time; we avoid
duplicating state across two tables at batch-generation time.
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0010_today_batch_items"
down_revision: str | Sequence[str] | None = "0009_lock_tables_rekey"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "today_batch_items",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column(
            "user_id",
            sa.Integer(),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("batch_date", sa.Date(), nullable=False),
        sa.Column(
            "company_id",
            sa.Integer(),
            sa.ForeignKey("companies.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("company_domain", sa.String(255), nullable=False),
        sa.Column(
            "to_contact_id",
            sa.Integer(),
            sa.ForeignKey("contacts.id", ondelete="CASCADE"),
            nullable=False,
        ),
        # JSON-encoded list[int] of contact IDs for CC recipients.
        sa.Column("cc_contact_ids", sa.String(), nullable=False, server_default="[]"),
        sa.Column(
            "template_id",
            sa.Integer(),
            sa.ForeignKey("templates.id"),
            nullable=True,
        ),
        sa.Column("subject", sa.String(512), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("send_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "status", sa.String(16), nullable=False, server_default="default"
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.UniqueConstraint(
            "user_id",
            "batch_date",
            "company_id",
            name="uq_today_batch_user_date_company",
        ),
    )
    op.create_index(
        "idx_today_batch_user_date",
        "today_batch_items",
        ["user_id", "batch_date"],
    )
    op.create_index("idx_today_batch_status", "today_batch_items", ["status"])


def downgrade() -> None:
    op.drop_index("idx_today_batch_status", table_name="today_batch_items")
    op.drop_index("idx_today_batch_user_date", table_name="today_batch_items")
    op.drop_table("today_batch_items")
