"""TodayBatchItem ORM model — one row per company outreach per user per day.

Generated by the B5.4 batch cron. Consumed by:
  - /today router (GET): hydrate the user's daily review cards
  - /today router (PATCH): user edits subject/body/status/send_time
  - B5.5 send worker (future): drain rows with status='ready' at send_time

The `cc_contact_ids` column stores a JSON-encoded list[int]. We keep the
ser/de on the model itself via classmethods so callers don't have to remember
the encoding contract.
"""
from __future__ import annotations

import json
from datetime import date, datetime

from sqlalchemy import (
    Date,
    DateTime,
    ForeignKey,
    Integer,
    String,
    Text,
    UniqueConstraint,
)
from sqlalchemy.orm import Mapped, mapped_column

from app.db.base import Base
from app.models._mixins import TimestampMixin


class TodayBatchItem(Base, TimestampMixin):
    __tablename__ = "today_batch_items"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    user_id: Mapped[int] = mapped_column(
        ForeignKey("users.id", ondelete="CASCADE"), nullable=False
    )
    batch_date: Mapped[date] = mapped_column(Date, nullable=False)
    company_id: Mapped[int] = mapped_column(
        ForeignKey("companies.id", ondelete="CASCADE"), nullable=False
    )
    company_domain: Mapped[str] = mapped_column(String(255), nullable=False)
    to_contact_id: Mapped[int] = mapped_column(
        ForeignKey("contacts.id", ondelete="CASCADE"), nullable=False
    )
    cc_contact_ids: Mapped[str] = mapped_column(String, nullable=False, default="[]")
    template_id: Mapped[int | None] = mapped_column(ForeignKey("templates.id"))
    subject: Mapped[str] = mapped_column(String(512), nullable=False)
    body: Mapped[str] = mapped_column(Text, nullable=False)
    send_time: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    status: Mapped[str] = mapped_column(String(16), nullable=False, default="default")
    # Set whenever the user manually edits subject or body via PATCH. Template
    # swaps (which re-render from a template) do NOT set this — they're a fresh
    # render, not a manual edit. Used by POST /today/apply-template to skip
    # cards that the user has personalized.
    edited_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    # Reason this card was set status='skipped' — e.g. "user_suspended",
    # "gmail_disconnected", "contact_missing_email", "reply_received". Used by
    # the admin dashboard + the followup planner to avoid spinning on items
    # that were explicitly skipped.
    skip_reason: Mapped[str | None] = mapped_column(String(64))

    # ─────────────────────────── follow-up support ───────────────────────────
    # 'initial' (default) = a fresh first-touch email; 'followup' = a follow-up
    # planned by the followup engine, sent on the SAME Gmail thread as the
    # original (subject "Re:…", In-Reply-To header set).
    kind: Mapped[str] = mapped_column(String(16), nullable=False, default="initial")
    # Set on follow-ups only: points back to the SendQueue row of the
    # originating email so we have its threadId / RFC822 Message-ID / body for
    # context display + threading.
    parent_send_queue_id: Mapped[int | None] = mapped_column(
        ForeignKey("send_queue.id", ondelete="SET NULL")
    )
    # 1 = first follow-up, 2 = second. Caps at MAX_FOLLOWUPS (config).
    followup_index: Mapped[int | None] = mapped_column(Integer)

    __table_args__ = (
        UniqueConstraint(
            "user_id", "batch_date", "company_id", name="uq_today_batch_user_date_company"
        ),
    )

    # ─────────────────────────── cc helpers ───────────────────────────

    @staticmethod
    def encode_cc(cc_ids: list[int]) -> str:
        """JSON-encode a list of contact IDs for the cc_contact_ids column."""
        return json.dumps(list(cc_ids))

    def get_cc_contact_ids(self) -> list[int]:
        """Decode the cc_contact_ids blob. Returns [] on missing/malformed."""
        if not self.cc_contact_ids:
            return []
        try:
            decoded = json.loads(self.cc_contact_ids)
        except json.JSONDecodeError:
            return []
        if not isinstance(decoded, list):
            return []
        return [int(x) for x in decoded if isinstance(x, int) or str(x).isdigit()]

    def set_cc_contact_ids(self, cc_ids: list[int]) -> None:
        self.cc_contact_ids = self.encode_cc(cc_ids)
